language: python
sudo: false
dist: trusty
python:
- '3.6'
os:
- linux
script:
- python -m unittest discover
notifications:
  slack:
    - secure: sdE5H69dgeC8vy8//2JP/Pkp4HAuI+3hH0HQWLU39JR8KtqW0bkpLxy1/1aiRlNRYRC6IWCG+LMWL+H3Myf0Z+dm8PmX/0aGCcgFVszm/RE9ZhyQeDftonIg7Bftk6UgcSerrydBqdoW37tIbwuLm2vsoB7avuvEVjm9FXxfSUAQVuzhqB7HvK69V4VhneF/lMYLbn0W9hw/yFOUz7M43S04fliRAlTICPHRM6hfMQCukQPRkhuTFXSRSm5yquEeroD/6Pp4KENplHKj9tuhX1Nd4SBmTmfeB8B2tODPLlNWr/iWkaiUiS1rFuRt+hpHRmy+7A3ASUqVE5OdOy8ottRqlbZUjyhvLe6HSfULiChJgkiccePCwVonZcY7bo8eToF0KaoxfXsA4nS11r3TfHpbPrX6h3uJk2zE/xT+0xSW7KzmG9TGF8gIoAwCgWewuGtGugROWxLnfJyHwevTwz6ozbxbw9bOW4lhDrmvnStWX9gwe2Un+wSSbpZQtOKoyXIiRZ+ndKJGvBW+p4okOKGMZAdy1JnBIswLUoUt4dXuO183eWlZkKC2CKnZq94J2CJ3iQHIhp+lBtDWxsakvejpAohbz4hpA7j7ArqGBjJL2afZiDO3/YwDBvuVgREnLyb3LBZEG9MkSa61YKu+WmZP6Ji151TjzyGCpV1AvQI=
  on_success: always
