language: python

sudo: false

dist: trusty

python:
- '3.6'

os:
- linux

script:
- python -m unittest discover

notifications:
  slack:
    secure: "sXK3E5R7AwUJ6qFEz3noi3BorGf9gTdIGHMwqjV4qJPyvd3R71jzAeDlZ+8xrCUqQH7q05eswWpMg3TtDrgNlSYb9u2KlUJ92RpVP4dZFoiC5pLDA9EK3n1c/Wa/RgV54k76vhzZZf0H9RNRcVtEOSH+Ql6tiBqEc7SiGOfwDKqH/nNc0Zy//V8a+eZ1ptu/Vh1cp84uCJBbkEE8u22ZsMit/WbNnXgYx+H6OghONxP4HDREWaHGRih60NW4yr0HJBBt7m0+qeEGwGOxjT5sYVpDwuTq4NKmFT8Qoi/z/KsL0OayQronDdcpvdFi9QM6jiwqht6z7XKlyOk2YvPvxlGc2xIGQ3/d7jwT7QOYmFMSphlkDVm/sbrx7P2i6qEGtSivTwUzSj3xCPixApydVIwe+BuuPHrG0UJKfaS/1XFnhaiJmV7UEUjof19So2BSBs90nHcAIJ5Zl6vUxQu1TicP32NbqTdYKEsjuMxgcn6EOYKFvVQKZEVdh3Zksp6WvUeI7Wuye1ssiOH9andOBP6jU7xFJhNYu9S0lRWUHLrijEDQC0NukbQZ3VXB4C+aCMYoMUrDJZ9yx1qP4RunQzALtj7+7kqiEXQJnRaUCSextWU55WDN4+bwsBHzs7F7ZE+PMacwWhX4TADLOPJzLAvX0pzpy5naJBmq14H0fK8="
  on_success: always
