language: python

sudo: false
dist: trusty

python:
    - "3.6"

os:
    - linux

script:
  - python -m unittest discover

 notifications:
    slack: nlp-tokyo:36Xqey7o4uILHvshIdBZepUS
    email: false