#this value is curretnly ignores, the script will try to deduce format of embeddings automatically
type_vectors: 

#can specify multiple locations here
path_vectors: [/work/alex/data/vectors/explicit/Japanese/_factorized/explicit_BCCWJ_raw_m100_w2_svd_d1000,
               ]
#only makes sense for SVD embeddings
alpha: 0.7

#allowed values are 3CosAdd, 3CosAvg, PairDistance, LRCos and LRCosF
method: 3CosAdd

path_dataset: /work/alex/data/linguistic/datasets/analogies/Japanese

